
services:
  # Service MySQL
  mysql:
    image: mysql:8.0
    container_name: mini_blog_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mini_blog
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mini_blog_network

  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mini_blog_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - mini_blog_network

  # Service Nginx
  nginx:
    image: nginx:alpine
    container_name: mini_blog_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mini_blog_network

  # Service PHP-FPM
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_blog_php
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://root:root@mysql:3306/mini_blog?serverVersion=8.0.32&charset=utf8mb4
    depends_on:
      - mysql
    networks:
      - mini_blog_network

volumes:
  mysql_data:

networks:
  mini_blog_network:
    driver: bridge
