version: '3.8'

services:
  # Service Nginx
  nginx:
    image: nginx:alpine
    container_name: mini_blog_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mini_blog_network

  # Service PHP-FPM
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_blog_php
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=dev
      - APP_SECRET=your-secret-key
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
    networks:
      - mini_blog_network
    user: "1000:1000"

networks:
  mini_blog_network:
    driver: bridge
